### ISSUE TITLE
Container Overflowing

### ISSUE THREAD

**Issue by KunjSPatel** [davidgrzyb/laravel-ticketing-system#1]
The view all users screen shows the data overflowed when viewed on a cellphone. The webpage should be responsive when viewed from cell phone devices.

![webpage-overflowing-ticketsystem](https://user-images.githubusercontent.com/44912648/48591508-2be65a80-e912-11e8-8a12-b05e1221ebbf.jpeg)

**Comment by davidgrzyb** [comment]
I've fixed this by wrapping
`<div class="table-responsive"></div>`
around the table.
